spring:
  application:
    name: PetFriends_Transporte
  cloud:
    function:
      definition: pedidoDespachado
    stream:
      default-binder: pubsub
      bindings:
        pedidoDespachado-in-0:
          destination: PetFriends_Pedidos
    gcp:
      project-id: softwares-escalaveis
      credentials:
        location: <SUAS_CREDENCIAIS>

